### ISSUE TITLE
How to use with `plugins/docker` and `plugins/ecr`

### ISSUE THREAD

**Issue by joneshf-cn** [meltwater/drone-cache#147]
**Is your feature request related to a problem? Please describe.**

I cannot seem to figure out how to use this plugin with a step that uses [`plugins/ecr`][] (or its underlying plugin [`plugins/docker`][]). It seems like, since [`plugins/docker`][] uses docker-in-docker, that the files created/used in the `Dockerfile` are not available to this plugin. Does that seem about right? I imagine that I need to do something on my end in order to make the volume that this plugin uses available to the [`plugins/docker`][] plugin. Or, is there some other way?

**Describe the solution you'd like**

I'm not entirely sure this is a problem for this plugin to solve. If there's a solution that's out of band, maybe an example of how to solve it in the README.md would be good enough? Or at the very least, a link to where that solution is documented?

**Describe alternatives you've considered**

It seems like if I dump the steps in the `Dockerfile` into the step in `.drone.yml`, it would work. But, I don't want to do this since the `Dockerfile` is used for other things than just Drone and keeping the two in sync sounds unfun.

**Additional context**

[`plugins/docker`]: http://plugins.drone.io/drone-plugins/drone-docker/
[`plugins/ecr`]: http://plugins.drone.io/drone-plugins/drone-ecr/

**Comment by kakkoyun** [comment]
@joneshf-cn If I understand you correctly you somehow want to cache your intermediate image layers, so you are looking for a docker build cache? Am I correct? 

If it's the case, `drone-cache` doesn't intend to be a solution for that use cases.

I'd be glad if you could clarify your use case.

**Comment by joneshf-cn** [comment]
Sorry for being confusing.

I'm not looking for `drone-cache` to work with docker layers. What I'm saying is that I don't know how to make the cache available inside the `Dockerfile` used by `plugins/docker`/`plugins/ecr`.

**Comment by kakkoyun** [comment]
Oh got it right now. We need to check which volumes/directories are mounted and with which mechanism they get mounted.

**Comment by jimsheldon** [comment]
If I understand correctly, this plugin would have to be trusted to be able to run `docker load` or `docker save` to get layers into and out of the image cache on the host?

**Comment by joneshf-cn** [comment]
Oh. As in, there would need to be changes to `drone-cache` in order to make it work? If so, don't fret too much about it. It would be nice, and I won't shy away from something that works. But, I'm sure there's a different way to get caching with `plugins/ecr` that doesn't involve y'all doing a bunch of work.

**Comment by jimsheldon** [comment]
@joneshf-cn you could definitely achieve docker image layer caching with drone as long as you can run `docker load` and `docker save` commands in your pipeline somehow.

Unfortunately, accessing the docker socket on the host would require your repo to be [trusted](https://docs.drone.io/quickstart/cli/#trusted-mode). If you are running your own hosted drone instance, that setting is something you can change.  However, you can't make your repo trusted on cloud.drone.io.  The cloud.drone.io service only allows specific images to access the docker socket (like `plugins/docker` and `plugins/ecr`).

I'm going to close this out, since I don't think this could be built into this plugin.  Thanks for the suggestion though!
