### ISSUE TITLE
[docs] move "Future Work" section to GH issues instead

### ISSUE THREAD

**Issue by spier** [meltwater/drone-cache#64]
When looking at the [Future Work](https://github.com/meltwater/drone-cache#future-work) section in the README I was wondering if we should move this to github issues instead? 

When doing a quick grouping, I think that for the following feature ideas we already have issues (or could easily create new ones):

```
Add Azure Storage Backend
Add Google Cloud Storage Backend
Add s/FTP Backend
Add Alibaba OSS Backend
Add Microsoft Azure Storage Backend
```

The following look like chores/fixes/smaller features that we don't have issues for yet:

 ```
 Fix goreleaser/drone/docker conflicts or remove redundancy with Drone jsonnet
 Add cache key fallback list
 Flush or TTL/Retention policy
 Add unit tests
```

@kakkoyun if you hare happy for me to do so, I can create new issues for the missing ones, and then just point from the future work section to the https://github.com/meltwater/drone-cache/issues

What do you think?

**Comment by kakkoyun** [comment]
@spier I think this is a great idea. As you said before we have already moved a couple of those things to issues. Thanks in advance for your contributions.

Just one thing to point out, we may have a related issue(#50) about `Flush or TTL/Retention policy`, you may want to separate flush and TTL part.

I have been also trying to promote collaboration for the repo that's why I have put #hacktoberfest label to issue, we can also put it as a topic to the repo.

What do you think?

**Comment by spier** [comment]
Quick fix: Added `hacktoberfest` and `hacktoberfest2019` topics to the repo.

I will work on the rest of the issues/documentation later and reach out to you if I have questions.

**Comment by kakkoyun** [comment]
@spier I guess we could say this is done. What do you think?

**Comment by spier** [comment]
@kakkoyun yes, I think so. 

I am closing it.
